add HTTP version to connection and responses
Lukasa/hyper pull request #296
Opened 2016-12-01 18:24 UTC by nateprewitt

This should address #285.

The tests aren't passing right now because we still have an outstanding bug (#291) in hyper until a new version of h2 is released. Other than the b'connection' header failures though, everything seems to be working.

2016-12-01 18:35 UTC, nateprewitt commented
Actually it looks like TestImportPython2.test_cannot_import_python_2 is failing too because it raises an AttributeError rather than an ImportError.

This seems unrelated to this patch though. I can dig a bit if you don't immediately know what's causing that @Lukasa.

2016-12-01 22:01 UTC, Lukasa requested changes
This generally seems fine! I'll try to chase the test stuff up tomorrow.

2016-12-01 22:01 UTC, Lukasa commented on hyper/http20/connection.py
> +        self.version = HTTPVersion.http20
Given that these are static and don't change, let's set these on the class object rather than do this at initialisation time.

2016-12-01 22:01 UTC, Lukasa commented on test/test_hyper.py
> +
Can we also get a few tests for the abstract HTTPConnection object passing this through?

2016-12-02 05:51 UTC, nateprewitt commented
A couple quick questions on the abstract tests. I'm currently unable to come up with a way to test HTTP and TLS upgrades without live network IO to something like http2bin.org. I could mock the connections like the other tests but that kind of defeats the point.

The second question I have is more of an oddity. I've written what is a successful test when run with py.test and as a separate python file, but in tox it repeatedly fails to perform the TLS upgrade. `wrap_socket` never changes the proto from `None`.

```python
from hyper.common.connection import HTTPConnection
from hyper.common.util import HTTPVersion

c = HTTPConnection('www.http2bin.org', 443)
assert c.version is HTTPVersion.http11
c.request('GET', '/')
assert c.version is HTTPVersion.http20
```

2016-12-02 05:53 UTC, nateprewitt commented on test/test_abstraction.py
> +        c.get_response()
Note: test the response version here too.

2016-12-02 10:30 UTC, Lukasa commented
> I'm currently unable to come up with a way to test HTTP and TLS upgrades without live network IO to something like http2bin.org. I could mock the connections like the other tests but that kind of defeats the point.

I don't think I follow this. Other parts of the test suite have found a way to do it, it should be possible for your code to do that. In this case, you just need to lie about the connection setup, which ought not to be too difficult.

>  I've written what is a successful test when run with py.test and as a separate python file, but in tox it repeatedly fails to perform the TLS upgrade. wrap_socket never changes the proto from None.

Are you running the same Python version in both cases? Same dependencies? Almost certainly you're using a Python that has a too-old ssl library or OpenSSL in tox, so there is no negotiation.

2016-12-02 11:49 UTC, Lukasa commented
Ok, the master branch should have its tests fixed up.

2016-12-02 15:19 UTC, nateprewitt commented
> I don't think I follow this. Other parts of the test suite have found a way to do it, it should be possible for your code to do that. In this case, you just need to lie about the connection setup, which ought not to be too difficult.

Sorry, I should have been clearer. The other parts of the library are mocking out a custom Connection object in order to do this. In that case, I'm simply creating a DummySocket that has an attr "version" and then testing the dummy socket still has a version after upgrades. That kind of test never actually touches the underlying `HTTP11Connection`  or `HTTP20Connection` so it doesn't prove anything useful. It will always pass regardless of changes to the actual connection classes.

>Are you running the same Python version in both cases? Same dependencies? Almost certainly you're using a Python that has a too-old ssl library or OpenSSL in tox, so there is no negotiation.

That was the first thing I had checked but couldn't find anything immediately. The weird thing is it will run fine locally in a fresh virtualenv, but fails in tox and Travis. I'll try to do a deeper dig to figure out what my base environment has that doesn't seem to be in Travis.

2016-12-02 15:20 UTC, Lukasa commented
Hrm. Can you do it in the socket-level style by actually creating a TLS connection? If not, we may need to use some mocks to achieve what we need.

2016-12-02 15:44 UTC, nateprewitt commented
Yeah, I'll do some tinkering this afternoon and try to devise a way to initiate the upgrades with the actual objects but no external IO.

2016-12-06 10:28 UTC, Lukasa requested changes
So this looks good, except for the fact that one of the tests is super-wacky and I don't really understand what it was trying to do.

2016-12-06 10:28 UTC, Lukasa commented on test/test_abstraction.py
> +                b'Upgrade: TLS/1.0, HTTP/2.0'
Uh...what is this? This test doesn't make any sense at all, and frankly suggests that the upgrade code in hyper is broken. =P

2016-12-06 17:50 UTC, nateprewitt commented on test/test_abstraction.py
> +                b'Upgrade: TLS/1.0, HTTP/2.0'
Sorry, this one was a test based off of a bad reading of the RFC 2817. I had a question on it yesterday that I was going to ask here but solved it and forgot to remove the code.

I am however at a bit of a loss for testing an actual TLS upgrade. I can get it working from py.test but I'm back to the same problem with tox/Travis not finding ALPN or NPN. I'll upload where I'm at in a second.

2016-12-06 23:48 UTC, nateprewitt commented
@Lukasa, okay, sorry that took so long. I got the test working by monkeypatching `wrap_socket`. Things should be ready for an actual look now.

2016-12-07 00:39 UTC, nateprewitt commented
As an aside, is there a reason the tests are configured to pass despite failures, as long as there's 100% test coverage?

I hit this with a couple test attempts that were failing but the build wasn't explicitly telling me until I dug into the logs of "successful" builds. It looks like all of the NGHTTP2 builds have been failing to import nghttp2 (`TestUtilities.test_nghttp2_installs_correctly`) for at least the last few months too.

2016-12-07 08:24 UTC, Lukasa commented
There is not, I think it's just a misconfiguration of Travis. I seem to recall that I had the same problem in the hpack library, which I fixed in python-hyper/hpack#60. This included removing the nghttp2 support (which hasn't worked for a while, and which I didn't have the resources to investigate).

I recommend opening a PR to do both of those things if you have the bandwidth to do it. =)

2016-12-07 08:31 UTC, Lukasa requested changes
Small notes, but I think it'd be good if we tackled the bad reporting of tests first. =)

2016-12-07 08:31 UTC, Lukasa commented on test/test_integration.py
> +            send_event.set()
This needs to be `wait`, not `set`.

2016-12-07 10:21 UTC, Lukasa commented
Nevermind, I'm tackling it myself in #298.

2016-12-07 16:23 UTC, nateprewitt commented
Alright, things should be set once the tests finish.

2016-12-07 17:40 UTC, Lukasa approved these changes
Looks good to me, thanks @nateprewitt!

2016-12-07 17:40 UTC, merged