Add ENABLE_PUSH flag in the Upgrade HTTP2-Settings header
Lukasa/hyper pull request #311
Opened 2017-02-23 11:33 UTC by hkwi

Push flag required for the case the initial upgrade request triggered server push. This PR is a relaxed version of #310 , which was more strict on server push I/O timing.
Test send/recv timing was fixed, because connection state machine does not get corrupted during h2c upgrade migration.

2017-02-23 13:31 UTC, Lukasa requested changes
So this seems reasonable, but there are some changes in the tests I don't understand. Notes are inline.

2017-02-23 13:31 UTC, Lukasa commented on test/test_hyper.py
> +        self.frames.append(frame)
Can we move these helpers out to a common mixin class now that we're using them in more than one place?

2017-02-23 13:31 UTC, Lukasa commented on test/test_hyper.py
> +        self.conn.request('GET', '/')
I wonder if this should do any asserting that the Upgrade header is present?

2017-02-23 13:31 UTC, Lukasa commented on test/test_integration.py
> -            send_event.wait()
Why did this get moved?

2017-02-23 13:31 UTC, Lukasa commented on test/test_integration.py
> -            send_event.wait(5)
Why was this removed?

2017-02-23 14:38 UTC, hkwi commented on test/test_hyper.py
> +        self.frames.append(frame)
I got it.

2017-02-23 14:38 UTC, hkwi commented on test/test_hyper.py
> +        self.conn.request('GET', '/')
Upgrading process itself is tested at `test_http11.py`, and IMHO, we would focus on client side view here.

2017-02-23 14:46 UTC, Lukasa commented on test/test_hyper.py
> +        self.conn.request('GET', '/')
Yeah, that's fair enough.

2017-02-23 14:46 UTC, hkwi commented on test/test_integration.py
> -            send_event.wait()
We have to wait here only when the client side are going to get the response. Another option is add `send_event.wait()` here, and add `get_response()`, `send_event.set()` in client side.

2017-02-23 14:48 UTC, hkwi commented on test/test_integration.py
> -            send_event.wait(5)
We have to wait here when we close the socket. Another option is add `send_event.wait()` and `sock.close()` here, and `send_event.set()` in client side.

2017-02-23 14:49 UTC, Lukasa commented on test/test_integration.py
> -            send_event.wait()
So historically the reason for these waits has been to ensure that we don't close sockets in a way that leads to unexpected socket behaviour on some platforms. If we don't *need* to remove them I'd be inclined to leave them in.

2017-02-23 14:50 UTC, Lukasa commented on test/test_integration.py
> -            send_event.wait(5)
I don't think this really answered what the reason was for removing this. Was it causing a problem?

2017-02-23 14:51 UTC, hkwi commented on test/test_integration.py
> -            send_event.wait()
OK

2017-02-23 15:24 UTC, hkwi commented on test/test_integration.py
> -            send_event.wait(5)
It does not causing problem. I removed just because I thought it was not necessary.

2017-02-23 15:33 UTC, Lukasa commented on test/test_integration.py
> -            send_event.wait(5)
Yeah, for this stuff that's not really a great attitude. Specifically, these are intended to delay socket shutdown to the point where the socket is no longer in use, as some interactions can cause exceptions to be raised if EOF is received too early.

2017-02-23 16:42 UTC, Lukasa requested changes

2017-02-23 16:42 UTC, Lukasa commented on test/test_hyper.py
> +
Why did all these blank lines get added?

2017-02-23 16:45 UTC, hkwi commented on test/test_hyper.py
> +
Ah... that's autopep8. I'd revert those.

2017-02-23 17:01 UTC, Lukasa requested changes
Ok, cool, getting closer. One more question inline.

2017-02-23 17:01 UTC, Lukasa commented on test/test_integration.py
> +    while len(got) < len(client_preface) and time.time() < timeout:
What's the logic behind this timeout here? The socket doesn't actually have the timeout applied to it, so it could time out indefinitely.

2017-02-23 17:09 UTC, hkwi commented on test/test_integration.py
> +    while len(got) < len(client_preface) and time.time() < timeout:
Oh, that's a bug. I used timeout for local testing.

2017-02-24 08:44 UTC, Lukasa approved these changes
Cool, this looks good to me. Thanks for doing all this work @hkwi! :sparkles:

2017-02-24 08:44 UTC, merged