Respect `verify` option in requests adapter
Lukasa/hyper pull request #321
Opened 2017-05-06 10:56 UTC by KostyaEsmukov

2017-05-06 10:58 UTC, KostyaEsmukov commented on test/test_hyper.py
> +        assert conn._conn.ssl_context.verify_mode == ssl.CERT_REQUIRED
I would like to ensure here that ssl_context has really loaded the passed CA file, but I can't find a way to check this.

2017-05-06 12:53 UTC, Lukasa requested changes
Thanks, this looks reasonable to me! I have a few small notes inline, but nothing drastic.

2017-05-06 12:53 UTC, Lukasa commented on test/test_hyper.py
> +            cert=CLIENT_PEM_FILE)
Can we validate the client cert is being set?

2017-05-06 12:53 UTC, Lukasa commented on test/test_hyper.py
> +        assert conn._conn.ssl_context.verify_mode == ssl.CERT_REQUIRED
Yeah, sadly you can't. =( This is one of the many deficiencies of the OpenSSL interface we have access to.

2017-05-06 16:23 UTC, KostyaEsmukov commented on test/test_hyper.py
> +            cert=CLIENT_PEM_FILE)
I don't think so, I can't find it in the `SSLContext` API.
Maybe we could try an integration test instead?

2017-05-06 18:01 UTC, Lukasa commented on test/test_hyper.py
> +            cert=CLIENT_PEM_FILE)
Yeah, that's a good point, I forgot that there was no API for it. Let's just let it ride for now I guess. :grin:

2017-05-24 08:39 UTC, StephanDollberg commented
Anything missing on this? Otherwise, I could help getting this over the finish line.

2017-05-24 17:16 UTC, Lukasa approved these changes

2017-05-24 17:16 UTC, merged

2020-10-06 05:48 UTC, vikramojha89 commented
Can you reopen the issue, I am still getting this issue with below script:

```
Accept_header = {'Accept': 'application/xhtml+xml;v=2.0'}

basic_auth = HTTPBasicAuth("User", "Password")

print(type(basic_auth))

s = requests.Session()

s.mount('https://127.0.0.1:443', HTTP20Adapter())
r = s.get('https://127.0.0.1:443/ctrl', auth=basic_auth, headers=Accept_header, verify=False)
print(r.status_code)
```

`ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1076)`